# Generated by Django 4.0.2 on 2022-02-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='price',
            field=models.FloatField(max_length=100),
        ),
    ]
